---
- name: Check azcli version
  gather_facts: false
  shell: "az version 2>&1 | head -n 2 |grep -q {{azcli_version}}"
  failed_when: false
  changed_when: false
  register: azcli_versions_match

- include: download-debian.yml
  when: azcli_versions_match.rc != 0

- name: Add Microsoft Package Repository Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: azcli_versions_match.rc != 0

- name: Add Microsoft Package Repository
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main'
    state: present
    update_cache: yes
  when: azcli_versions_match.rc != 0

- name: Install Microsoft Azure CLI
  apt:
    name: azure-cli={{ azcli_version }}
    state: present
    update_cache: yes
  when: azcli_versions_match.rc != 0
